// src/components/Sidebar.vue
<template>
  <div class="page-container">
    <md-app md-waterfall md-mode="fixed">
      <md-app-toolbar class="md-primary">
        <span class="md-title">Split</span>
      </md-app-toolbar>

      <md-app-drawer md-permanent="full">
        <md-toolbar class="md-transparent" md-elevation="0">
          <md-menu md-size="auto" class="fill">
            <md-button md-menu-trigger class="fill">
              <md-avatar class="md-large">
                <img
                  :src="selectedAccount.imageUrl"
                  alt="Current account avatar"
                />
              </md-avatar>
              {{ selectedAccount.username }}
              <md-icon>arrow_drop_down</md-icon>
            </md-button>

            <md-menu-content>
              <md-menu-item
                :class="{ selected: selectedAccount.id === 0 }"
                @click="selectAccount(0)"
              >
                Multi-account
              </md-menu-item>
              <md-divider />
              <md-menu-item
                v-for="account in accounts"
                :key="account.id"
                :class="{ selected: selectedAccount === account }"
                @click="selectAccount(account.id)"
              >
                <md-avatar>
                  <img :src="account.imageUrl" alt="Account avatar" />
                </md-avatar>
                {{ account.username }}
              </md-menu-item>
              <md-divider />
              <md-menu-item :to="{ name: 'Sign' }">Log Out</md-menu-item>
            </md-menu-content>
          </md-menu>
        </md-toolbar>

        <NavList v-if="!isDialogsPage" />
        <md-tabs v-else md-alignment="fixed" md-active-tab="tab-dialogs">
          <md-tab id="tab-pages" md-label="Pages">
            <NavList />
          </md-tab>
          <md-tab id="tab-dialogs" md-label="Dialogs">
            <md-list class="md-double-line padding-0">
              <md-list-item
                v-for="preview in dialogsPreviews"
                :key="preview.id"
                :to="{ name: 'Dialogs', params: { id: preview.id } }"
              >
                <md-avatar>
                  <img :src="preview.pictureSrc" alt="Dialog image" />
                </md-avatar>
                <div class="md-list-item-text">
                  <span class="flex">
                    <span class="inline bold flexFill">{{ preview.name }}</span>
                    <span class="inline right unsetOverflow">{{ preview.dateTimeStr }}</span>
                  </span>
                  <span>
                    <strong>
                      {{ preview.isDraft ? "Draft" : preview.isCurrentAccount(selectedAccount.id) ? "You" : preview.shortUsername }}:
                    </strong>
                    {{ preview.text }}
                  </span>
                </div>
                <md-badge v-if="preview.unreadMessagesCount > 0" :md-content="preview.unreadMessagesCount" />
              </md-list-item>
            </md-list>
          </md-tab>
        </md-tabs>
      </md-app-drawer>

      <md-app-content>
        <slot></slot>
      </md-app-content>
    </md-app>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import Account from "@/data/Account";
import NavList from "@/components/NavList.vue";
import DialogPreview from "@/data/DialogPreview";

@Component({
  components: { NavList }
})
export default class Sidebar extends Vue {
  selectAccount(id: number) {
    this.$store.commit("accounts/selectAccount", id);
  }

  get dialogsPreviews(): DialogPreview[] {
    return this.$store.getters["dialogsPreviews/getPreviews"];
  }

  get selectedAccount(): Account {
    return this.$store.state.accounts.selected;
  }

  get accounts(): Account[] {
    return this.$store.state.accounts.accounts;
  }

  get isDialogsPage(): boolean {
    return this.$route.name === "Dialogs";
  }
}
</script>

<style scoped>
.selected >>> * {
  font-weight: bold;
}

.md-toolbar {
  padding: 0;
}

.md-drawer {
  width: 240px;
}

.md-button {
  text-transform: none;
}

.md-button >>> .md-ripple > .md-button-content {
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.md-button >>> .md-ripple > .md-button-content > * {
  margin: unset;
}

.md-list-item >>> .md-list-item-content {
  justify-content: flex-start;
}

.md-tab {
  padding: 0;
}

.md-tabs >>> .md-tab-nav-button {
  min-width: 0 !important;
}

.padding-0 {
  padding: 0 !important;
}

.inline {
  display: inline;
}

.flex {
  display: flex;
}

.flexFill {
  flex: 1 1 auto !important;
  min-width: 0;
}

.bold {
  font-weight: bold;
}

.right {
  float: right;
}

.unsetOverflow {
  overflow: unset;
  width: auto;
}
</style>

// src/app/parts/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AccountsService } from '../../services/accounts.service';
import { Account } from '../../data/account';
import { DialogsPreviewsService } from '../../services/dialogs-previews.service';
import { DialogPreview } from '../../data/dialog-preview';
import {DialogsService} from '../../services/dialogs.service';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css', '../../css/thumbnails.css']
})
export class SidebarComponent implements OnInit {
  accounts: Account[] = [];
  previews: DialogPreview[] = [];
  unreadMessagesCount = 0;
  selectedAccount: Account;
  constructor(private readonly accountsService: AccountsService,
              private readonly dialogsService: DialogsService,
              private readonly previewsService: DialogsPreviewsService,
              public readonly router: Router) {
    this.dialogsService.sidebarCallback = () => this.updateValues();
  }

  ngOnInit(): void {
    this.accounts = this.accountsService.getAccounts();
    this.updateValues();
  }
  changeAccount(id: number): void {
    this.accountsService.selectAccount(id);
    this.updateValues();
  }
  updateValues(): void {
    this.selectedAccount = this.accountsService.getSelected();
    this.previews = this.previewsService.getPreviews();
    this.unreadMessagesCount = this.previews.reduce((c, p) => c + p.unreadMessagesCount, 0);
  }
}

<div class="bg-light border-right" id="sidebar-wrapper">
  <div id="accounts-part">
    <!-- Profile picture -->
    <img matListAvatar src="{{selectedAccount.imageUrl}}" class="thumbnail" alt="Profile picture"/>
    <!-- Username -->
    <strong>{{selectedAccount.username}}</strong>
    <!-- Dropdown button -->
    <button mat-icon-button aria-label="Accounts dropdown button" [matMenuTriggerFor]="accountsMenu">
      <mat-icon>arrow_drop_down</mat-icon>
    </button>
    <mat-menu #accountsMenu="matMenu">
      <button mat-menu-item (click)="changeAccount(0)" [style.font-weight] = "selectedAccount.id === 0 ? 'bold' : ''" matTooltip="Operate from multi-account">Multi-account</button>
      <mat-divider></mat-divider>
      <!-- Accounts -->
      <button mat-menu-item *ngFor="let account of accounts" (click)="changeAccount(account.id)">
        <img src="{{account.imageUrl}}" class="small-thumbnail" alt="Account picture"/>
        <span class="flex-fill align-self-center " [style.font-weight] = "selectedAccount.id === account.id ? 'bold' : ''">
            {{account.username}}
          </span>
      </button>
      <!-- /Accounts -->
      <mat-divider></mat-divider>
      <a mat-menu-item href="./sign" matTooltip="Sign out of multi-account">Log Out</a>
    </mat-menu>
  </div>
  <ng-container *ngIf="router.isActive('/dialogs', false) else navTemplate">
    <!--suppress HtmlUnknownAttribute -->
    <mat-tab-group mat-stretch-tabs selectedIndex="1">
      <mat-tab label="Pages">
        <ng-container *ngTemplateOutlet="navTemplate"></ng-container>
      </mat-tab>
      <mat-tab label="Dialogs">
        <mat-nav-list *ngFor="let preview of previews">
          <mat-list-item [routerLink]="['/dialogs', preview.id]">
            <img matListAvatar class="thumbnail" [src]="preview.pictureSrc" alt="Dialog picture">
            <div mat-line class="dialog-preview-line">
              <strong>{{preview.name}}</strong>
              <span>{{preview.dateTimeStr}}</span>
            </div>
            <div mat-line [matBadgeHidden]="preview.unreadMessagesCount<=0" [matBadge]="preview.unreadMessagesCount" matBadgeColor="accent" matBadgeSize="small">
              <strong>{{preview.isDraft ? 'Draft' : preview.isCurrentAccount(selectedAccount.id) ? 'You' : preview.shortUsername}}:</strong>
              {{preview.text}}
            </div>
          </mat-list-item>
        </mat-nav-list>
      </mat-tab>
    </mat-tab-group>
  </ng-container>

  <ng-template #navTemplate>
    <mat-nav-list>
      <a mat-list-item routerLink="" routerLinkActive="active" [routerLinkActiveOptions]="{exact:true}">Main</a>
      <a mat-list-item routerLink="/dialogs" routerLinkActive="active">
        <span [matBadgeHidden]="unreadMessagesCount<=0" [matBadge]="unreadMessagesCount" matBadgeColor="accent" matBadgeOverlap="false" matBadgeDescription="Number of unread messages">Dialogs</span>
      </a>
      <a mat-list-item routerLink="/comments" routerLinkActive="active" [routerLinkActiveOptions]="{exact:true}">
        <span matBadge="3" matBadgeColor="accent" matBadgeOverlap="false" matBadgeDescription="Number of unreacted comments">My comments</span>
      </a>
      <a mat-list-item routerLink="/settings" routerLinkActive="active">Settings</a>
    </mat-nav-list>
  </ng-template>
</div>
